# nao temos sensores, o que fazer com isso
obstacle_range: 2.5   # Range de leitura maximo do sensor no costmap
raytrace_range: 3.0   # Distancia em que o robo comeca a prever trajetorias
footprint: [[1, 1], [1, -1], [-1, -1], [-1, 1]] # posicao das rodas sendo [0,0] o centro do robo
inflation_radius: 0.55 # trata obstaculos a 0.55m com peso igual

#observation_sources: laser_scan_sensor point_cloud_sensor # sensores que passam informacao para o costmap

# sconfig dos sesores 
# laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}