global_costmap:
  global_frame: map
  transform_tolerance: 0.5
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 3.0
  resolution: 0.05
  static_map: true # deixar true se usarmos map_server
  rolling_window: false
  width: 100.0
  height: 100.0
  origin: [-15.400000, -13.800000, 0.000000]
  #max_obstacle_height: 0.6
  
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    #- {name: inflation_layer,         type: "costmap_2d::InflationLayer"}