global_costmap:
  global_frame: map
  transform_tolerance: 0.5
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 3.0
  resolution: 0.05
  static_map: true # deixar true se usarmos map_server
  rolling_window: false
  max_obstacle_height: 0.6

  static_map: true

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}