local_costmap:
  transform_tolerance: 0.5
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true #Indica se o costmap ficará centrado no robô conforme ele anda
  resolution: 0.05
  max_obstacle_height: 0.3

  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}